using System.IO;
using System.Text;

namespace TimelineRuntimeExtension
{
    static class CmdRegisterGenerate
    {
        const string FileName = "RegisterCmd.cs";
        const string Waring = "// Waring: This file is generated by TimelineRuntimeExtension. Forbidden edition!";
        public static void Generate()
        {
            CodeGenerateConfig.MakeSureGenenrateDirectory();
            var code = new StringBuilder();
            code.AppendLine(Waring);
            code.AppendLine($"namespace {typeof(CmdRegisterGenerate).Namespace}");
            code.AppendLine("{");
            code.AppendLine($"    static partial class {typeof(CmdFactory).Name}");
            code.AppendLine("    {");
            code.AppendLine("        public static void InitCmdRegister()");
            code.AppendLine("        {");
            foreach(var type in CodeGenerateConfig.GetAllCmdCodeGenerateTypes()) 
            {
                string className = CodeGenerateConfig.GetCmdName(type);
                code.AppendLine($"            RegisterCreateFunc(\"{className}\", () => {{ return new {className}(); }});");
            }
            code.AppendLine("        }");
            code.AppendLine("    }");
            code.AppendLine("}");
            code.AppendLine(Waring);
            string filePath = Path.Combine(CodeGenerateConfig.FolderPath, FileName);
            File.WriteAllText(filePath, code.ToString());
        }
    }
}
