// Waring: This file is generated by TimelineRuntimeExtension. Forbidden edition!
namespace TimelineRuntimeExtension
{
    static partial class CmdFactory
    {
        public static void InitCmdRegister()
        {
            RegisterCreateFunc("CmdTest1Clip", () => { return new CmdTest1Clip(); });
            RegisterCreateFunc("CmdTest2Clip", () => { return new CmdTest2Clip(); });
        }
    }
}
// Waring: This file is generated by TimelineRuntimeExtension. Forbidden edition!
